- name: Provision infrastructure
  hosts: all
  become: true

  roles:
    - role: docker_engine
      tags:
        - docker

    - role: traefik
      tags:
        - traefik

    - role: garage
      tags:
        - garage

    - role: timescaledb
      tags:
        - timescaledb
        - database

    - role: monitoring
      tags:
        - monitoring
