- name: Provision infrastructure
  hosts: all
  become: true

  roles:
    - role: base
      tags: base

    - role: ssh
      tags:
        - ssh

    - role: firewall
      tags:
        - firewall

    - role: docker_engine
      tags:
        - docker

    - role: traefik
      tags:
        - traefik

    - role: security
      tags:
        - security

    - role: garage
      tags:
        - garage

    - role: timescaledb
      tags:
        - timescaledb
        - database

    - role: monitoring
      tags:
        - monitoring
