name: Ansible CI

on:
  push:
    paths:
      - "ansible/**"
      - "ansible.cfg"
      - ".github/workflows/ci-ansible.yml"

  pull_request:
    paths:
      - "ansible/**"
      - "ansible.cfg"
      - ".github/workflows/ci-ansible.yml"

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Ansible tools
        run: pip install ansible-core ansible-lint

      - name: Install Ansible collections
        run: ansible-galaxy collection install -r ansible/requirements.yml

      - name: Ansible syntax check - provision
        run: ansible-playbook --syntax-check ansible/playbooks/provision.yml

      - name: Ansible lint
        run: ansible-lint ansible/
