name: ci

on:
  push:
  pull_request:

jobs:
  lint-validate:
    name: Lint et validation Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"

      - name: Lint (terraform fmt)
        run: terraform fmt -check -recursive

      - name: Init
        run: terraform init -backend=false

      - name: Validate (terraform validate)
        run: terraform validate
